### ISSUE TITLE
Report workflow fails if project does not have any annotations

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science#1223]
It seems like nearly all reports would have annotations, but we should probably handle for their absence.

<img width="1680" alt="image" src="https://github.com/archesproject/arches-for-science-prj/assets/1877663/19063291-45c1-4f30-961f-e2e842bde255">

**Comment by chiatt** [comment]
I'm leaving this open because although #1264 did a lot to help prevent errors, it's still possible to create a project, add a phys thing, upload chemical analysis data, and then try to create a report. The report will fail on the last step.

**Comment by jacobtylerwalls** [comment]
@chiatt just retested, and all looks good for me. Can you still reproduce an issue?

**Comment by chiatt** [comment]
Thanks @jacobtylerwalls - If it's working for you, I'll go ahead and close this.
